feat: SQSCANGHA-6 add ability to pass certificate to action
SonarSource/sonarqube-scan-action pull request #37
Opened 2022-08-17 06:23 UTC by Aeolun

Since the solution to this problem seemed kind of straightforward to me, and I was having this same issue, here is a fix. This should make it easier for any other person with this problem to  add certificates through an environment variable going forward.

Fixes #26

2022-08-23 20:35 UTC, dbmeneses approved these changes
Minor comments otherwise LGTM. @wouter-admiraal-sonarsource could you please review it as well?

2022-08-23 20:35 UTC, dbmeneses commented on entrypoint.sh
> +  keytool -keystore /etc/ssl/certs/java/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias sonarqube -file /tmp/tmpcert.pem
I'd add `rm /tmp/tmpcert.pem`

2022-08-23 20:35 UTC, dbmeneses commented on README.md
> +- `SONAR_ROOT_CERT` – This is used to pass the scanner a custom root certificate (in PEM format), that should be used for validating the sonarqube server certificate. You can set the `SONAR_ROOT_CERT
```suggestion
- `SONAR_ROOT_CERT` – Holds an additional root certificate (in PEM format) that is used to validate the SonarQube server certificate. You can set the `SONAR_ROOT_CERT` environment variable in the "Secrets" settings page of your repository, or you can add them at the level of your GitHub organization (recommended).
```

2022-08-24 07:16 UTC, wouter-admiraal-sonarsource requested changes
There is one change need in the example, otherwise LGTM.

2022-08-24 07:16 UTC, wouter-admiraal-sonarsource commented on README.md
> +If your sonarqube server users a self-signed certificate, you can pass a root certificate (in PEM format) to use for validation to the java certificate store:
Nitpicking:

```suggestion
If your SonarQube server users a self-signed certificate, you can pass a root certificate (in PEM format) to use for validation to the java certificate store:
```

2022-08-24 07:16 UTC, wouter-admiraal-sonarsource commented on README.md
> +        SONAR_ROOT_CERT: %{{ secrets.SONAR_ROOT_CERT }}
```suggestion
        SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
```

2022-08-25 11:37 UTC, ilostmyrepo reviewed
accept

2022-08-30 20:44 UTC, dbmeneses commented
@Aeolun when you get a chance please address the feedback so that we can merge this PR

2022-09-21 01:53 UTC, marcocrasso commented
Is there any ETA for this to get merged?

2022-09-26 14:44 UTC, wouter-admiraal-sonarsource commented on README.md
> +If your SonarQube server users a self-signed certificate, you can pass a root certificate (in PEM format) to use for validation to the java certificate store:
```suggestion
If your SonarQube server uses a self-signed certificate, you can pass a root certificate (in PEM format) to the java certificate store:
```

2022-09-26 14:45 UTC, wouter-admiraal-sonarsource commented on entrypoint.sh
> +  echo "${SONAR_ROOT_CERT}" > /tmp/tmpcert.pem
```suggestion
  rm -f /tmp/tmpcert.pem
  echo "${SONAR_ROOT_CERT}" > /tmp/tmpcert.pem
```

2022-09-26 14:45 UTC, wouter-admiraal-sonarsource approved these changes

2022-09-26 14:47 UTC, merged